spring.application.name=spring-ai-conference-app-agent-local
spring.ai.bedrock.aws.region=us-east-1
spring.ai.bedrock.aws.timeout=10m
spring.ai.bedrock.converse.chat.options.max-tokens=100
spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0
spring.ai.mcp.client.type=SYNC

cognito.user.pool.name=UserPoolForAgentCoreMCP
cognito.user.pool.client.name=UserPoolClientWithUserAndPasswordForAgentCoreMCP
cognito.auth.token.resource.server.id=AgentCoreResourceServerId


amazon.bedrock.agentcore.gateway.base.url=https://web-search-gateway-4kp2gwxstr.gateway.bedrock-agentcore.us-east-1.amazonaws.com
amazon.bedrock.agentcore.gateway.endpoint=/mcp

logging.level.root=INFO
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.client=DEBUG
logging.level.io.modelcontextprotocol.client.transport=DEBUG
logging.level.io.modelcontextprotocol.spec=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
